apiVersion: v1
kind: Pod
metadata:
  name: gary-re
  labels:
    k8s-app: gary-re
  namespace: sbks
spec:
  containers:
  - name: gary-re
    image: jiaweitang/sbks-torch:latest
    imagePullPolicy: Always
    args: ["sleep", "36500000"]
    resources:
      limits:
        memory: "4G"
        cpu: 1
        nvidia.com/gpu: 0
      requests:
        memory: "4G"
        cpu: 1
        nvidia.com/gpu: 0
    volumeMounts:
      - mountPath: "/sbksvol"
        name: sbksvol
    env:
    - name: PYTHONPATH
      value: "/sbksvol/jiawei/sbks-ucsd/relation-extraction/biobert_RE"
  restartPolicy: Never
  automountServiceAccountToken: false
  volumes:
    - name: sbksvol
      persistentVolumeClaim:
        claimName: sbksvol
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: gary-re
  name: gary-re
  namespace: sbks
spec:
  type: ClusterIP
  ports:
  - port: 8888
    name: web
  selector:
    k8s-app: gary-re
