apiVersion: v1
kind: Pod
metadata:
  name: gary-re
  labels:
    k8s-app: gary-re
  namespace: sbks
spec:
  containers:
  - name: gary-re
    image: jiaweitang/sbks-torch:latest
    imagePullPolicy: Always
    args: ["sleep", "36500000"]
    resources:
      limits:
        memory: "8G"
        cpu: 2
        nvidia.com/gpu: 1
      requests:
        memory: "8G"
        cpu: 2
        nvidia.com/gpu: 1
    volumeMounts:
      - mountPath: "/sbksvol"
        name: sbksvol
    env:
    - name: PYTHONPATH
      value: "/sbksvol/jiawei/sbks-ucsd/relation-extraction/biobert_RE"
  restartPolicy: Never
  volumes:
    - name: sbksvol
      persistentVolumeClaim:
        claimName: sbksvol
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gpu-type
            operator: In
            values:
            - 2080Ti
            - 1080Ti
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: gary-re
  name: gary-re
  namespace: sbks
spec:
  type: ClusterIP
  ports:
  - port: 8888
    name: web
  selector:
    k8s-app: gary-re
