apiVersion: batch/v1
kind: Job
metadata:
  name: eric-test # name this like <user>-<extra>
  namespace: sbks
spec:
  template:
    spec:
      nodeSelector:
        # nodeName: k8s-bharadia-03
        # nautilus.io/region: ucsd
      containers:
      - name: bert-xl-alias
        image: nakumgaurav/sbks:dev8
        # image: tensorflow/tensorflow  
        command:
        - sh
        - -c
        args:
        - "bash /sbksvol/eric/sbks-ucsd/top-model/huggingface-finetune/run_test.sh Cellline_cellfinder_baseline_v10_lr5_6_wd3_ft5_pt10_tp3 Cellline cellfinder baseline_v10_lr5_6_wd3_ft5_pt10_tp3 1 > /sbksvol/eric/Cellline_cellfinder_baseline_v10_lr5_6_wd3_ft5_pt10_tp3.txt"
        resources:
          limits:
            memory: "8G"
            cpu: 1
            ephemeral-storage: "1G"
            nvidia.com/gpu: 1  # enable GPUs as needed
          requests:
            memory: "8G"
            cpu: 1
            ephemeral-storage: "1G"
            nvidia.com/gpu: 1  # must match the limit!
        volumeMounts:
          - mountPath: "/sbksvol"
            name: sbksvol
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "ls && eval $(ssh-agent -s) && mkdir -p ~/.ssh && ssh-add ~/../etc/secret-volume/ssh-privatekey && /root/anaconda3/bin/python3.7 -m pip install transformers==4.6.0 pytorch-crf==0.7.2 \"ray[tune]\"==1.9.2 wandb=0.12.9"]
      restartPolicy: Never
      volumes:
        - name: sbksvol
          persistentVolumeClaim:
            claimName: sbksvol
  backoffLimit: 0  # no backoff; if pod fails, fail the job
