apiVersion: v1
kind: Pod
metadata:
  name: gary-re
  labels:
    k8s-app: gary-re
  namespace: sbks
spec:
  containers:
  - name: gary-re
    image: jiaweitang/sbks-torch:latest
    imagePullPolicy: Always
    args: ["sleep", "36500000"]
    resources:
      limits:
        memory: "6G"
        cpu: 1.5
        nvidia.com/gpu: 1
      requests:
        memory: "6G"
        cpu: 1.5
        nvidia.com/gpu: 1
    volumeMounts:
      - mountPath: "/sbksvol"
        name: sbksvol
    env:
    - name: PYTHONPATH
      value: "/root/sbks-ucsd/relation-extraction/biobert_RE"
    - name: GITLAB_TOKEN
      valueFrom: 
        secretKeyRef: 
          name: re-gitlab-readonly
          key: token
  restartPolicy: Never
  automountServiceAccountToken: false
  volumes:
    - name: sbksvol
      persistentVolumeClaim:
        claimName: sbksvol
    - name: re-gitlab-readonly
      secret:
        secretName: re-gitlab-readonly
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: nvidia.com/gpu.product
              operator: In
                # Specifies GPU types
              values:
                - NVIDIA-GeForce-RTX-2080-Ti
                - NVIDIA-GeForce-RTX-1080-Ti
