apiVersion: v1
kind: Pod
metadata:
  name: non-mpi
  labels:
          app: something
          rel:  dev
spec:
      restartPolicy: Never
      serviceAccountName: jbentley2
      nodeSelector:
        brightcomputing.com/node-category: 'gaudi'
      volumes:
      - name: home
        hostPath:
          path: /home/jbentley2
          type: Directory
      - name: scratch
        emptyDir: {}

      containers:
      - name: gaudi-container  
        image: vault.habana.ai/gaudi-docker/1.11.0/ubuntu22.04/habanalabs/pytorch-installer-2.0.1:1.11.0-587
        workingDir: /home/jbentley2/relation-extraction
        resources:
          requests:
            cpu: 48
            memory: 409Gi
            habana.ai/gaudi: 8
            hugepages-2Mi: 95000Mi
          limits:
            cpu: 48
            memory: 409Gi
            habana.ai/gaudi: 8
            hugepages-2Mi: 95000Mi
        volumeMounts:
        - name: home
          mountPath: /home/jbentley2
        - name: scratch
          mountPath: /scratch
        env:
        - name: POD_NAME_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NODE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        workingDir: /home/jbentley2/relation-extraction
        command: ["/bin/bash", "-c"]
        args: ["sleep 80000s"]