apiVersion: v1
kind: Pod
metadata:
        name: pt-pod
spec:
        restartPolicy: Never
        volumes:
          - name: mydir
            hostPath:
              path: /home/jbentley2
              type: Directory
        containers:
        - name: gaudi-container
          image: vault.habana.ai/gaudi-docker/1.11.0/ubuntu22.04/habanalabs/pytorch-installer-2.0.1:1.11.0-587
          workingDir: /home/jbentley2/relation-extraction
          volumeMounts:
            - name: mydir
              mountPath: /home/jbentley2
          command: ["/bin/sh", "-c"]
          args: ["sleep 80000s"]
          resources:
            requests:
               cpu: 8
               memory: 32Gi
               habana.ai/gaudi: 1
               hugepages-2Mi: 3600Mi
            limits:
               cpu: 8
               memory: 64Gi
               habana.ai/gaudi: 1
               hugepages-2Mi: 3600Mi