apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sbksvol
  namespace: sbks
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
