apiVersion: v1
kind: Pod
metadata:
  name: sbks-jiawei-gpu
  labels:
    k8s-app: sbks-jiawei-gpu
  namespace: sbks
spec:
  containers:
  - name: sbks-jiawei-gpu
    # image: sdsc/words-tensorflow-py3:latest
    image: jiaweitang/sbks-biobert
    imagePullPolicy: Always
    # args: ["sleep", "36500000"]
    #args: ["python3", "/usr/local/bin/jupyter-notebook", "--ip=*", "--port=8888", "--allow-root", "--NotebookApp.iopub_data_rate_limit=2147483647"]
    resources:
      limits:
        memory: "8G"
        cpu: 2
        nvidia.com/gpu: 1
      requests:
        memory: "8G"
        cpu: 2
        nvidia.com/gpu: 1
    volumeMounts:
      - mountPath: "/sbksvol"
        name: sbksvol
  restartPolicy: Never
  volumes:
    - name: sbksvol
      persistentVolumeClaim:
        claimName: sbksvol

