apiVersion: v1
kind: Pod
metadata:
  name: gau-cpu
  labels:
    k8s-app: gau-cpu
  namespace: sbks
spec:
  containers:
  - name: gau-cpu
    # image: sdsc/words-tensorflow-py3:latest
    # image: gitlab-registry.nautilus.optiputer.net/greencodes/images/master/tf20-jupyter-dask:latest
    image: nakumgaurav/sbks:dev6
    imagePullPolicy: Always
    args: ["sleep", "36500000"]
    #args: ["python3", "/usr/local/bin/jupyter-notebook", "--ip=*", "--port=8888", "--allow-root", "--NotebookApp.iopub_data_rate_limit=2147483647"]
    resources:
      limits:
        memory: "8G"
        cpu: 1
        nvidia.com/gpu: 0
      requests:
        memory: "8G"
        cpu: 1
        nvidia.com/gpu: 0
    volumeMounts:
      - mountPath: "/sbksvol"
        name: sbksvol
  restartPolicy: Never
  volumes:
    - name: sbksvol
      persistentVolumeClaim:
        claimName: sbksvol
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: gau-cpu
  name: gau-cpu
  namespace: sbks
spec:
  type: ClusterIP
  ports:
  - port: 8888
    name: web
  selector:
    k8s-app: gau-cpu
