apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: examplevol
  namespace: satellite-unicef
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi