apiVersion: v1
kind: Pod
metadata:
  name: mai
  labels:
    k8s-app: mai
spec:
  containers:
  - name: mai
    image: sdsc/words-tensorflow-py3
    imagePullPolicy: Always
    #args: ["sleep", "36500000"]
    #args: ["python3", "/usr/local/bin/jupyter-notebook", "--ip=*", "--port=8888", "--allow-root", "--NotebookApp.iopub_data_rate_limit=2147483647"]
    resources:
      limits:
        memory: "24G"
        cpu: 2
        nvidia.com/gpu: 1
      requests:
        cpu: 2
        nvidia.com/gpu: 1
    volumeMounts:
      - mountPath: "/cephfs"
        name: cephfs
  restartPolicy: Never
  volumes:
    - name: cephfs
      flexVolume:
        driver: ceph.rook.io/rook
        fsType: ceph
        options:
          fsName: nautilusfs
          clusterNamespace: rook
          path: /fuelmap
          mountUser: fuelmap
          mountSecret: ceph-fs-secret
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: mai
  name: mai
spec:
  type: NodePort
  ports:
  - port: 8888
    name: web
  selector:
    k8s-app: mai
