apiVersion: v1
kind: Pod
metadata:
  name: topic-modeling
  labels:
    k8s-app: topic-modeling
  namespace: sbks
spec:
  containers:
  - name: topic-modeling
    image: duxiang/sbks:topic-modeling
    imagePullPolicy: Always
    args: ["sleep", "36500000"]
    resources:
      limits:
        memory: "8G"
        cpu: 1
        nvidia.com/gpu: 0
      requests:
        memory: "8G"
        cpu: 1
        nvidia.com/gpu: 0
    volumeMounts:
      - mountPath: "/sbksvol"
        name: sbksvol
  restartPolicy: Never
  volumes:
    - name: sbksvol
      persistentVolumeClaim:
        claimName: sbksvol
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: topic-modeling
  name: topic-modeling
  namespace: sbks
spec:
  type: ClusterIP
  ports:
  - port: 8888
    name: web
  selector:
    k8s-app: topic-modeling
