apiVersion: v1
kind: Pod
metadata:
  name: kgqa-pod
spec:
  containers:
  - name: kgqa
    image: aarthy22/kgqa 
    resources:
      limits:
        memory: "12G"
        cpu: 1
        nvidia.com/gpu: 2
      requests:
        memory: "12G"
        cpu: 1
        nvidia.com/gpu: 2
    command: ["sh", "-c", "echo 'Im a new pod' && sleep infinity"]
    volumeMounts:
    - mountPath: "/sbksvol"
      name: sbksvol
  volumes:
    - name: sbksvol
      persistentVolumeClaim:
        claimName: sbksvol
  affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-RTX-2080-Ti
                - NVIDIA-GeForce-GTX-1080-Ti
