apiVersion: batch/v1
kind: Job
metadata:
  name: myapp1
  namespace: sbks
spec:
  template:
    spec:
      nodeSelector:
        nautilus.io/region: ucsd
      containers:
      - name: demo1
        # image: sdsc/words-tensorflow-py3
        image: gitlab-registry.nautilus.optiputer.net/greencodes/images/master/tf20-jupyter-dask:latest
        command: ["bash", "/sbksvol/misc_tests/job_test.sh", "myapp1"] # place the shell script here, or anywhere you want but remember to change the path
        resources:
          limits:
            memory: "2G"
            cpu: 1
            nvidia.com/gpu: 0  # enable GPUs as needed
          requests:
            memory: "2G"
            cpu: 1
            nvidia.com/gpu: 0  # must match the limit!
        volumeMounts:
          - name: sbksvol
            mountPath: "/sbksvol"
      restartPolicy: Never
      volumes:
        - name: sbksvol
          flexVolume:
            driver: ceph.rook.io/rook
            fsType: ceph
            options:
              fsName: nautilusfs
              clusterNamespace: rook
              # path: /fuelmap
              # mountUser: fuelmap
              # mountSecret: ceph-fs-secret
  backoffLimit: 0  # no backoff; if pod fails, fail the job
