apiVersion: batch/v1
kind: Job
metadata:
  name: myapp6
  namespace: sbks
spec:
  template:
    spec:
      nodeSelector:
        nautilus.io/region: ucsd
      containers:
      - name: demo1
        image: nakumgaurav/sbks:dev6
        command:
        - sh
        - -c
        args:
        - "/usr/bin/python3.6 -m pip install --upgrade pip &&
        pip install tensorflow==1.13.1 && pip3 install --user tensorflow-gpu==1.13.1 && pip install keras==2.3.1 && 
        pip install git+https://www.github.com/keras-team/keras-contrib.git &&
        bash /sbksvol/xiang/sbks_gitlab/top-model/BIOBERT/NER/src/models/job_test_prediction.sh"
        resources:
          limits:
            memory: "8G"
            cpu: 4
            nvidia.com/gpu: 0  # carefully monitor when using GPU
          requests:
            memory: "4G"
            cpu: 4
            nvidia.com/gpu: 0 
        volumeMounts:
          - mountPath: "/sbksvol"
            name: sbksvol
      restartPolicy: Never
      volumes:
        - name: sbksvol
          persistentVolumeClaim:
            claimName: sbksvol
  backoffLimit: 0