apiVersion: batch/v1
kind: Job
metadata:
  name: aarthy-gcn-re
  labels:
    k8s-app: aarthy-gcn-re
  namespace: sbks
spec:
  backoffLimit: 0
  template:
    spec:
      automountServiceAccountToken: false
      containers:
      - name: aarthy-gcn-re
        image: jiaweitang/sbks-torch:latest
        command:
        - "/bin/bash"
        - "-c"
        - >
          cd /root &&
          git clone https://aarthy-22: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@github.com/aarthy-22/sbks-gcn.git &&
          cd /root/sbks-gcn/GCN-BERT &&
          conda install boto3 nltk pandas scipy=1.4.1 && 
          mkdir ../data/merged/predictions &&
          mkdir ../data/merged/predictions/binary &&
          mkdir ../data/merged/predictions/final &&
          mkdir ../data/merged/predictions/initial &&
          python run.py
        imagePullPolicy: Always
        resources:
          limits:
            memory: "20G"
            cpu: 2
            nvidia.com/gpu: 2
          requests:
            memory: "20G"
            cpu: 2
            nvidia.com/gpu: 2
        volumeMounts:
          - mountPath: "/sbksvol"
            name: sbksvol
          - mountPath: /dev/shm
            name: dshm
      restartPolicy: Never
      volumes:
        - name: sbksvol
          persistentVolumeClaim:
            claimName: sbksvol
        - name: dshm
          emptyDir:
            medium: Memory
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-RTX-2080-Ti
                - NVIDIA-GeForce-GTX-1080-Ti
